<h3 align='center'> Numpy</h3>

In [223]:
import numpy as np

In [224]:
#initialising an array
a=np.array([1,2,3,4])
print(a)
b = np.array([[1,2,3],[2,3,4]])
print(b)

[1 2 3 4]
[[1 2 3]
 [2 3 4]]


In [225]:
#to get the dimension of an array
print(a.ndim)
print(b.ndim)

1
2


In [226]:
#to understand the shape of an array
b.shape

(2, 3)

In [227]:
#get data type
b.dtype

dtype('int64')

Accessing/Changing specific elements, rows,columns,etc

In [228]:
arr1=np.array([[1,2,3,4,5,6],[7,8,9,1,2,3]])
print(arr1)

[[1 2 3 4 5 6]
 [7 8 9 1 2 3]]


In [229]:
#get a specific element [r,c]
arr1[1,5]

np.int64(3)

In [230]:
#get a specific row
arr1[1, :]

array([7, 8, 9, 1, 2, 3])

In [231]:
#getting some specific elements using indexing [start index,end index,step size]
print(arr1[0,0:-1:2])
print(arr1[0,1:-1:2])
print(arr1[1,0:-1:2])
print(arr1[1,1:-1:2])

[1 3 5]
[2 4]
[7 9 2]
[8 1]


In [232]:
#changing the value of an element
print(arr1)
arr1[1,5]=20
print(arr1)

[[1 2 3 4 5 6]
 [7 8 9 1 2 3]]
[[ 1  2  3  4  5  6]
 [ 7  8  9  1  2 20]]


In [233]:
arr2=np.array([[[11,12,13,14],[15,16,17,18]],[[21,22,23,24],[25,26,27,28]]])
print(arr2)

[[[11 12 13 14]
  [15 16 17 18]]

 [[21 22 23 24]
  [25 26 27 28]]]


In [234]:
arr2.shape

(2, 2, 4)

In [235]:
#getting specific element in 3-D array
arr2[0,1,3]

np.int64(18)

In [236]:
#getting some specific elements using indexing [start index,end index,step size]
print(arr2[0,0,1:4:2])
print(arr2[1,0,1:4:2])
print(arr2[0,1,1:4:2])
print(arr2[1,1,1:4:2])

[12 14]
[22 24]
[16 18]
[26 28]


Initializing different types of arrays

In [237]:
#all zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [238]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [239]:
#all ones matrix
np.ones((2,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [240]:
#any other number matrix
#np.full((shape),number)
np.full((2,3),44,dtype='float32')

array([[44., 44., 44.],
       [44., 44., 44.]], dtype=float32)

In [241]:
#to get the shape of any other matrix previously created
np.full_like(arr2,11)

array([[[11, 11, 11, 11],
        [11, 11, 11, 11]],

       [[11, 11, 11, 11],
        [11, 11, 11, 11]]])

In [242]:
#a random integer valued array
np.random.randint(2,6,size=(3,3)) #here 2,6 indicates the range through which the random numbers to be selected

array([[4, 3, 4],
       [3, 5, 2],
       [5, 2, 5]], dtype=int32)

In [243]:
#the identity matrix
np.identity(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [244]:
#attaching one array to other
o=np.ones((5,5))
print(o)
z=np.zeros((3,3))
print(z)
z[1,1]=9
z[1:3]
o[1:-1,1:-1]=z #this [1:-1,1:-1] means, first row to the last row and then first column to the last column
print(o)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [245]:
before=np.array([[22,32,44,333,21,32],[22,12,87,67,55,88]])
print(before)
after=before.reshape([3,4])
print(after)

[[ 22  32  44 333  21  32]
 [ 22  12  87  67  55  88]]
[[ 22  32  44 333]
 [ 21  32  22  12]
 [ 87  67  55  88]]


NUMPY ARANGE

In [246]:
x=np.arange(5) #only stop is given
print(x)

[0 1 2 3 4]


In [247]:
y=np.arange(3,9) #start and stop given 
print(y)

[3 4 5 6 7 8]


In [248]:
z=np.arange(4,15,2) #with step
print(z)

[ 4  6  8 10 12 14]


In [249]:
ar=np.arange(1,11)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [250]:
ar1=np.arange(20,41,2)
print(ar1)

[20 22 24 26 28 30 32 34 36 38 40]


In [251]:
#Create an array of 20 random integers (1–50) and extract only the odd numbers.
ar2=np.random.randint(1,50,size=20)
print(ar2)
odd_ar2=ar2[ar2%2==1]
print("odd random array: ",odd_ar2)

[ 7 10 17 44 46  7 48 49 13 31 32 37 23 42 41 21 30 37 14 20]
odd random array:  [ 7 17  7 49 13 31 37 23 41 21 37]


In [252]:
#Compare memory usage of a Python list vs a NumPy array with 1000 elements.
import sys
py_list=list(range(1000))
np_array=np.arange(1000)
list_mry=sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)
array_mry=np_array.nbytes
print(f"memory used by python list {list_mry} bytes")
print(f"memory used bt numpy array {array_mry} bytes")

memory used by python list 36056 bytes
memory used bt numpy array 8000 bytes


In [253]:
#Reshape a NumPy array of numbers 1–36 into a 6×6 matrix.
bef=np.arange(1,37)
print(bef)
aft=bef.reshape([6,6])
print(aft)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


### DAY 2


In [254]:
arr= np.array([[3,3,4],[54,34,21]])
arr

array([[ 3,  3,  4],
       [54, 34, 21]])

In [255]:
print(arr[0,2])
print(arr[0,-2])
arr[1,1]=11
print(arr)
arr[0]+10

4
3
[[ 3  3  4]
 [54 11 21]]


array([13, 13, 14])

## SLICING

In [256]:

arr[:]

array([[ 3,  3,  4],
       [54, 11, 21]])

In [257]:
print(arr[1,0:3])
print(arr[0:1])
print(arr[0:1,2:]) #to fetch a specific element inside a row

[54 11 21]
[[3 3 4]]
[[4]]


In [258]:
ar1=np.array([[1,3,4,5],[5,6,7,8],[9,0,10,11],[12,13,14,15]])
ar1

array([[ 1,  3,  4,  5],
       [ 5,  6,  7,  8],
       [ 9,  0, 10, 11],
       [12, 13, 14, 15]])

In [259]:
print(ar1[1:3,0:2])

[[5 6]
 [9 0]]


In [260]:
print(ar1[0:3:2,0:3]) #to skip a row in between give steps in the row section


[[ 1  3  4]
 [ 9  0 10]]


### BROADCASTING

In [261]:
ar01=np.array([11,22,33])
print(ar01)
ar02=np.array([10,20,30])
print(ar02)

[11 22 33]
[10 20 30]


In [262]:
ar01+ar02

array([21, 42, 63])

In [263]:
ar01 + 10

array([21, 32, 43])

In [264]:
ar01=np.array([1,2,3]) #1x3 Array
print(ar01)
ar02=np.array([[2],[4],[6]]) #3x1 Array
print(ar02)

[1 2 3]
[[2]
 [4]
 [6]]


##### logically we can't add a 3x1 and 1x3 array together, but in numpy it's possible and it's called BROADCASTING

In [265]:
ar01+ar02

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

#### what happened there in the addition is that: the 1x3 matrix became 1 2 3 and the 3x1 matrix became 2 2 2
                    1 2 3                           4 4 4
                    1 2 3                           6 6 6

In [266]:
ar01=np.array([1,2,3]) #1x3 Array
print(ar01)
ar02=np.array([[2,2,2],[4,4,4]]) #2x3 Array
print(ar02)

[1 2 3]
[[2 2 2]
 [4 4 4]]


In [267]:
ar01+ar02

array([[3, 4, 5],
       [5, 6, 7]])

#### the addition of 1x3 and 2x3 is possible through numpy broadcasting in such a way that the 1x3 array have changed to 1 2 3 which is a 2x3 array
                       1 2 3 

### ELEMENT WISE OPERATION  

In [268]:
a=np.array([[2,1,1],[2,1,1]])
print(a)
b=np.array([[1,2,3],[3,2,1]])
print(b)

[[2 1 1]
 [2 1 1]]
[[1 2 3]
 [3 2 1]]


In [269]:
print("addition: ",a+b) 
print("subtraction: ",a-b)
print("multiplication: ",a*b)
print("division: ",a/b)
print("power: ",a**b)


addition:  [[3 3 4]
 [5 3 2]]
subtraction:  [[ 1 -1 -2]
 [-1 -1  0]]
multiplication:  [[2 2 3]
 [6 2 1]]
division:  [[2.         0.5        0.33333333]
 [0.66666667 0.5        1.        ]]
power:  [[2 1 1]
 [8 1 1]]


In [270]:
print("addition: ",b+a) 
print("subtraction: ",b-a)
print("multiplication: ",b*a)
print("division: ",b/a)
print("power: ",b**a)

addition:  [[3 3 4]
 [5 3 2]]
subtraction:  [[-1  1  2]
 [ 1  1  0]]
multiplication:  [[2 2 3]
 [6 2 1]]
division:  [[0.5 2.  3. ]
 [1.5 2.  1. ]]
power:  [[1 2 3]
 [9 2 1]]


In [271]:
print(a+5)
print(b*2)

[[7 6 6]
 [7 6 6]]
[[2 4 6]
 [6 4 2]]


In [272]:
#mathematical functions
print("square root of a: ",np.sqrt(a))
print("exponential of a: ",np.exp(a))
print("natural log of a: ",np.log(a))


square root of a:  [[1.41421356 1.         1.        ]
 [1.41421356 1.         1.        ]]
exponential of a:  [[7.3890561  2.71828183 2.71828183]
 [7.3890561  2.71828183 2.71828183]]
natural log of a:  [[0.69314718 0.         0.        ]
 [0.69314718 0.         0.        ]]


In [273]:
#boolean operations
c=np.array([True,False,True,False])
d=np.array([False,False,True,True])
print("AND: ",np.logical_and(c,d))
print("OR: ",np.logical_or(c,d))
print("NOT: ",np.logical_not(c,d))

AND:  [False False  True False]
OR:  [ True False  True  True]
NOT:  [False  True False  True]


### Functions: min(), max(), argmin(), argmax()

In [274]:
ar01=np.array([1,2,3])
print("minimum value: ",np.min(ar01))
print("maximum value: ",np.max(ar01))
print("index of minimum value: ",np.argmin(ar01))
print("index of maximum value: ",np.argmax(ar01))

minimum value:  1
maximum value:  3
index of minimum value:  0
index of maximum value:  2


In [275]:
#Slice a 2D array into sub-arrays.
d2=np.array([[1,1,1,1],[2,2,2,2]])
print(d2)
print(d2[0,:])
print(d2[1,:])

[[1 1 1 1]
 [2 2 2 2]]
[1 1 1 1]
[2 2 2 2]


In [276]:
#Find row-wise max, column-wise min.
ar1=np.array([[9,3,6,5],[34,6,42,8],[9,0,10,11],[12,29,71,15]])
print(ar1)
print("max of each row: ",np.max(ar1,axis=1))
print("min of each column: ",np.min(ar1,axis=0))

[[ 9  3  6  5]
 [34  6 42  8]
 [ 9  0 10 11]
 [12 29 71 15]]
max of each row:  [ 9 42 11 71]
min of each column:  [9 0 6 5]


In [277]:
#Perform broadcasting .
ar1=np.array([9,3,6,5]) #1x4 matrix
ar3=np.array([[3],[3],[3],[3]]) #4x1 matrix
print(ar1+ar3)

[[12  6  9  8]
 [12  6  9  8]
 [12  6  9  8]
 [12  6  9  8]]


In [278]:
#Slice the first 5 elements from an array of numbers 1–20.
ar20=np.arange(1,21)
print(ar20)
print(ar20[:5])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5]


In [279]:
#Extract the diagonal elements of a 4×4 matrix.
dia=np.random.randint(1,20,size=(4,4))
print(dia)
print(np.diag(dia))


[[18  2 13 17]
 [ 4  4  6 19]
 [12  3  4  1]
 [15 14 13  9]]
[18  4  4  9]


In [280]:
#Replace all negative values in an array with 0.
rep=np.random.randint(-20,20,size=(4,4))
print(rep)
new_rep=np.where(rep<0,0,rep) 
print(new_rep)

[[-15   2  -6  12]
 [ -8   9 -17 -11]
 [ 12  14 -14  -4]
 [-16  -3 -18  -5]]
[[ 0  2  0 12]
 [ 0  9  0  0]
 [12 14  0  0]
 [ 0  0  0  0]]


###### what happens here in the above question is that 
###### condition → Boolean array (True/False for each element).

###### x → values to use where condition is True.

###### y → values to use where condition is False.

###### It returns a new array of the same shape as the input.

In [281]:
#Create a 10×10 array and set the border elements to 1, inner elements to 0.
ar10=np.zeros((10,10),dtype=int)
print(ar10)
ar10[0,:]=1
ar10[-1,:]=1
ar10[:,0]=1
ar10[:,-1]=1
print(ar10)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [282]:
#Create a 5×5 random integer array (1–50) and replace all values greater than 25 with 99.
gr25=np.random.randint(1,50,size=(5,5))
print(gr25)
new_gr25=np.where(gr25>=25,99,gr25)
print(new_gr25)

[[40 30 49 43 22]
 [30 48 34 46 18]
 [ 8 20 35 18 10]
 [19 17 11  6 26]
 [13  1 37 12 31]]
[[99 99 99 99 22]
 [99 99 99 99 18]
 [ 8 20 99 18 10]
 [19 17 11  6 99]
 [13  1 99 12 99]]


In [283]:
#Create a 6×6 array and extract the top-left 3×3 subarray.
tl=np.random.randint(1,10,size=(6,6))
print(tl)
print(tl[:3,:3])


[[8 7 7 6 3 7]
 [7 7 5 6 5 6]
 [6 2 8 8 6 2]
 [8 6 3 8 9 3]
 [6 4 8 6 4 2]
 [8 4 1 6 3 3]]
[[8 7 7]
 [7 7 5]
 [6 2 8]]


In [284]:
#From a 5×5 array of numbers 1–25, extract all elements in the last 2 rows and last 3 columns.
l23=np.random.randint(1,10,size=(5,5))
print(l23)
print(l23[-2:,-3:])

[[5 1 3 1 9]
 [6 4 1 1 5]
 [5 6 1 9 5]
 [2 2 8 5 9]
 [7 1 1 5 5]]
[[8 5 9]
 [1 5 5]]


In [285]:
#Slice a 4×4 array into four 2×2 subarrays.
f22=np.arange(16).reshape(4,4)
print(f22)
subf1=f22[:2,:2]
subf2=f22[:2,2:24]
subf3=f22[2:4,2:4]
subf4=f22[2:4,:2]
print(subf1)
print(subf2)
print(subf3)
print(subf4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
[[10 11]
 [14 15]]
[[ 8  9]
 [12 13]]


In [286]:
#Find the row-wise sum and column-wise mean of a 4×4 array.
rcsm=np.arange(16).reshape(4,4)
print(rcsm)
print("row wise sum: ",np.sum(rcsm,axis=1))
print("column eise mean: ",np.mean(rcsm,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
row wise sum:  [ 6 22 38 54]
column eise mean:  [6. 7. 8. 9.]


In [287]:
#For a 3×5 random integer array (1–100), find the maximum of each row and the minimum of each column.
mrmc=np.random.randint(1,100,size=(3,5))
print(mrmc)
print("maximum of each row: ",np.max(mrmc,axis=1))
print("minimum of each column: ",np.min(mrmc,axis=0))

[[92  3 28 55 61]
 [74 13 73 69 94]
 [79  5 85 56 65]]
maximum of each row:  [92 94 85]
minimum of each column:  [74  3 28 55 61]


## DAY 3
#### Array Reshaping & Manipulation

#### Reshape , Flatten , Ravel , Transpose

In [288]:
res=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(res)
reshaped=res.reshape(3,4)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [289]:
flattened=reshaped.flatten()
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [290]:
raveled=reshaped.ravel()
print(raveled)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


###### the difference between flatten() and ravel() is that although they seemingly do the same function of making a multidimensional array into a 1D array, 
###### the flatten() function makes a copy of original array and then change it into 1D
###### while the ravel() function changes the original array to view like 1D array , therefore when we make any change in the raveled array , it will effect the original array
###### transpose() is used to interchange the rows and columns 

In [291]:
tr=np.random.randint(2,7,size=(3,4))
print(tr)
print("transpose: ")
print(tr.transpose())

[[2 4 4 4]
 [6 6 4 6]
 [2 3 4 3]]
transpose: 
[[2 6 2]
 [4 6 3]
 [4 4 4]
 [4 6 3]]


In [292]:
#Convert a 1D array into 2D (3×4).
d1_d2=np.arange(12)
print(d1_d2)
d2=d1_d2.reshape(3,4)
print(d2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [293]:
#Flatten a matrix into 1D.
print(d2)
flattened2=d2.flatten()
print(flattened2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [294]:
#Transpose a 2D array.
print(d2)
print("transpose: ")
print(d2.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpose: 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [295]:
#Create an array of numbers 1–12 and reshape it into a 3×4 matrix.
arr=np.arange(25)
print(arr)
print("reshaped: ")
print(arr.reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
reshaped: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [296]:
#Transpose a 2×3 matrix into a 3×2 matrix.
tr=np.random.randint(2,25,size=(2,3))
print(tr)
print("transpose: ")
print(tr.transpose())

[[16 16 11]
 [21 14 24]]
transpose: 
[[16 21]
 [16 14]
 [11 24]]


In [297]:
#Reshape numbers 0–29 into a 6×5 matrix and extract the 3rd column.
rr=np.arange(30)
print(rr)
print("reshaped to 6x5: ")
rr1=rr.reshape(6,5)
print(rr1)
print("3rd column: ")
print(rr1[:,2:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
reshaped to 6x5: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
3rd column: 
[[ 2]
 [ 7]
 [12]
 [17]
 [22]
 [27]]


In [298]:
#Flatten a 3×3 matrix and sort elements in descending order.
des=np.random.randint(0,9,size=(3,3))
print(des)
print("flattened: ")
des1=des.flatten()
print(des1)
print("in descending order: ")
print(np.sort(des1)[::-1])

[[3 3 3]
 [3 5 2]
 [7 2 2]]
flattened: 
[3 3 3 3 5 2 7 2 2]
in descending order: 
[7 5 3 3 3 3 2 2 2]


In [369]:
#Create an 8×8 checkerboard pattern using only zeros() and slicing.
# A checkerboard pattern is a grid of alternating black and white (or 0 and 1) squares — like the board used for chess or checkers.
cb=np.zeros((8,8),dtype=int)
print(cb)
cb[::2,1::2]=1 #even rows, odd columns
cb[1::2,::2]=1 #odd rows , even columns
print(cb)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [300]:
#Create a 5×5 identity matrix (diagonal = 1, others = 0).
idm=np.identity(5,dtype=int)
print(idm)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [301]:
#Generate an array of 20 random integers between 10 and 99, and reshape it into a 4×5 matrix.
res=np.random.randint(10,99,size=(4,5))
print(res)

[[85 84 14 69 23]
 [82 87 48 32 32]
 [90 46 79 85 70]
 [48 50 96 23 17]]


In [302]:
#Extract all even numbers from an array of numbers 1–30.
e=np.arange(1,31)
print(e)
e1=np.where(e%2==0)
print("this is the positions(indices) of even numbers in e")
print(e1)
e2=e[np.where(e%2==0)]
print("this is the even numbers: ")
print(e2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
this is the positions(indices) of even numbers in e
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]),)
this is the even numbers: 
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [303]:
#Replace all numbers divisible by 3 with -1 in an array of numbers 1–15.
b3=np.arange(16).reshape(4,4)
print(b3)
b3r=np.where(b3%3==1,-1,b3)
print(b3r)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0 -1  2  3]
 [-1  5  6 -1]
 [ 8  9 -1 11]
 [12 -1 14 15]]


## DAY 4 
#### Joining, Splitting & Copying

In [304]:
import importlib, numpy
importlib.reload(numpy)
import numpy as np

print(type(np.array))


<class 'builtin_function_or_method'>


C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:129: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  _bootstrap._exec(spec, module)


In [305]:
array1= np.array([1,2,3,4])
array2=np.array([6,7,8,9])
print(array1,"\n",array2)
print("concatinating/joining these two arrays")
joined_array=np.concatenate((array1,array2))
print(joined_array)

print("#joining arrays along rows")
array3=np.array([[1,2,3,4],[5,6,7,8]])
print(array3)
array4=np.array([[9,8,7,6],[4,3,2,1]])
print(array4)
row_array=np.concatenate((array3,array4),axis=1)
print(row_array)

[1 2 3 4] 
 [6 7 8 9]
concatinating/joining these two arrays
[1 2 3 4 6 7 8 9]
#joining arrays along rows
[[1 2 3 4]
 [5 6 7 8]]
[[9 8 7 6]
 [4 3 2 1]]
[[1 2 3 4 9 8 7 6]
 [5 6 7 8 4 3 2 1]]


##### numpy.vstack() (Vertical Stack)

##### Meaning: Joins arrays vertically → row-wise.

##### Think of it like putting one array on top of the other.

##### It works along axis=0 for 2D arrays.

In [306]:
print(array1,"\n",array2)
print("VSTACK")
v=np.vstack((array1,array2))
print(v)

[1 2 3 4] 
 [6 7 8 9]
VSTACK
[[1 2 3 4]
 [6 7 8 9]]


In [307]:
print(array3,"\n",array4,"\n")
v1=np.vstack((array3,array4))
print(v1)

[[1 2 3 4]
 [5 6 7 8]] 
 [[9 8 7 6]
 [4 3 2 1]] 

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [4 3 2 1]]


##### numpy.hstack() (Horizontal Stack)

#### Meaning: Joins arrays horizontally → side by side, column-wise.

##### Think of it like putting two arrays next to each other.

#### It works along axis=1 for 2D arrays.

In [308]:
print(array1,"\n",array2)
print("HSTACK")
h=np.hstack((array1,array2))
print(h)

[1 2 3 4] 
 [6 7 8 9]
HSTACK
[1 2 3 4 6 7 8 9]


In [309]:
print(array3,"\n",array4,"\n")
h1=np.hstack((array3,array4))
print(h1)

[[1 2 3 4]
 [5 6 7 8]] 
 [[9 8 7 6]
 [4 3 2 1]] 

[[1 2 3 4 9 8 7 6]
 [5 6 7 8 4 3 2 1]]


#### np.split() is used to divide an array into multiple sub-arrays.
#### Works for 1D, 2D, or N-D arrays.
#### You can split equally or by indices
#### numpy.split(ary, indices_or_sections, axis=0)


In [310]:
print("SPLIT")
print(array1)
sparray1=np.split(array1,2) #split(array_name, no.of parts to split the array)
print(sparray1)

SPLIT
[1 2 3 4]
[array([1, 2]), array([3, 4])]


In [311]:
print(v1)
sp1array1=np.split(v1,2,axis=1) #split column into 2 parts
print(sp1array1)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [4 3 2 1]]
[array([[1, 2],
       [5, 6],
       [9, 8],
       [4, 3]]), array([[3, 4],
       [7, 8],
       [7, 6],
       [2, 1]])]


In [312]:
print(v1)
sp2array1=np.split(v1,2,axis=0)
print(sp2array1)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [4 3 2 1]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[9, 8, 7, 6],
       [4, 3, 2, 1]])]


In [313]:
print(array1)
spind=np.split(array1,[2,3])
print(spind)

[1 2 3 4]
[array([1, 2]), array([3]), array([4])]


##### COPY()
##### When you want a completely independent array.
##### Useful in array manipulation, functions, or loops where you don’t want the original to change.

In [314]:
a=np.array([1,2,3,4])
print("initial a : ",a)
b=a 
b[0]=100
print(a,"\n",b)
print("here both a and b changed the value at index 1 to 100,because b is not a copy of a , but an another reference")

initial a :  [1 2 3 4]
[100   2   3   4] 
 [100   2   3   4]
here both a and b changed the value at index 1 to 100,because b is not a copy of a , but an another reference


In [315]:
a=np.array([1,2,3,4])
b=a.copy() #deep copy of a to b 
c=a.view() #shallow copy of a to c

b[0]=100
print("a: ",a,"\nb: ",b)
c[0]=101
print("a after shallow copied to c: ",a,"\nc: ",c)


a:  [1 2 3 4] 
b:  [100   2   3   4]
a after shallow copied to c:  [101   2   3   4] 
c:  [101   2   3   4]


In [316]:
#Concatenate two arrays [1,2,3] and [4,5,6].
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print(ar1,"\n",ar2)
cp=np.concatenate((ar1,ar2))
print(cp)

[1 2 3] 
 [4 5 6]
[1 2 3 4 5 6]


In [317]:
#Stack two 3×3 identity matrices vertically.
id1=np.identity(3,dtype=int)
id2=np.identity(3,dtype=int)
vst=np.vstack((id1,id2))
print(vst)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [318]:
#Split an array of size 20 into 4 equal chunks.
ar20=np.arange(20)
print(ar20)
spar20=np.split(ar20,4)
print(spar20)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


In [319]:
#Show with code how modifying a .view() changes the original array but .copy() does not.
x=np.array([1,1,1,1])
y=x.copy()
z=x.view()
y[3]=100
print("x: ",x,"\ny: ",y)
z[3]=101
print("x: ",x,"\ny: ",y,"\nz: ",z)

x:  [1 1 1 1] 
y:  [  1   1   1 100]
x:  [  1   1   1 101] 
y:  [  1   1   1 100] 
z:  [  1   1   1 101]


In [320]:
#Create two arrays of shape (2×3) and horizontally stack them into a (2×6) array.
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(6,12).reshape(2,3)
print(arr1,"\n",arr2)
stacked_arrays=np.hstack((arr1,arr2))
print(stacked_arrays)
splitted_array=np.split(stacked_arrays,3,axis=1)
print(splitted_array)

[[0 1 2]
 [3 4 5]] 
 [[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[array([[0, 1],
       [3, 4]]), array([[2, 6],
       [5, 9]]), array([[ 7,  8],
       [10, 11]])]


In [321]:
#Create a 1D array of 12 elements, reshape it into a 3×4 array, then vertically split it into 3 sub-arrays.
d1=np.arange(12).reshape(3,4)
print(d1)
spv=np.split(d1,3,axis=0)
print(spv)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [322]:
#Create two arrays [1,2,3] and [4,5,6], stack vertically, make a .copy() of the result, and change an element in the copied array. Verify the original array is unchanged.
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1,"\n",a2)
stv=np.vstack((a1,a2))
stvc=stv.copy()
stvc[:,2:]=100
print("original: ",stv,"\ncopy: ",stvc)

[1 2 3] 
 [4 5 6]
original:  [[1 2 3]
 [4 5 6]] 
copy:  [[  1   2 100]
 [  4   5 100]]


## DAY 5
### Random & Numerical Computations


In [323]:
print(d1)
print("mean of entire d1: ",np.mean(d1))
print("row wise mean: ",np.mean(d1,axis=1))
print("column wise mean: ",np.mean(d1,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mean of entire d1:  5.5
row wise mean:  [1.5 5.5 9.5]
column wise mean:  [4. 5. 6. 7.]


In [336]:
print(d1)
print("overall median: ",np.median(d1))
print("row wise median: ",np.median(d1,axis=1))
print("column wise median: ",np.median(d1,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
overall median:  5.5
row wise median:  [1.5 5.5 9.5]
column wise median:  [4. 5. 6. 7.]


In [325]:
print(d1)
print("overall standard deviation: ",np.std(d1))
print("column wise standard deviation: ",np.std(d1,axis=0))
print("row wise standard deviation: ",np.std(d1,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
overall standard deviation:  3.452052529534663
column wise standard deviation:  [3.26598632 3.26598632 3.26598632 3.26598632]
row wise standard deviation:  [1.11803399 1.11803399 1.11803399]


In [326]:
ran=np.random.rand(3,4)
print(ran)


[[0.07828575 0.82833166 0.47280916 0.9978359 ]
 [0.82137332 0.63161307 0.20167436 0.1679257 ]
 [0.43259171 0.71008633 0.78002948 0.43913356]]


In [327]:
nrand=np.random.randn(2,3,4,5)
print(nrand)

[[[[-0.55415756  0.3331687  -1.51689668 -1.43188123 -1.08694279]
   [ 0.47159111 -0.40818028 -0.07149042  0.30990903 -1.036864  ]
   [-1.32226122  2.23676926  0.21167388  0.70668248 -0.29399746]
   [ 0.89325561  1.15736206  0.48267911  0.9073156  -1.10712479]]

  [[ 0.59223183 -0.00832402 -0.99654266  0.2617212  -0.59237547]
   [ 1.74936392  0.07885063  1.37586127 -0.60254324 -0.04666552]
   [-1.81876593  0.85872384 -0.03568269  0.14519612 -0.39774043]
   [ 1.50321543  0.74561375 -1.01564769 -0.39743273 -1.09585893]]

  [[-0.09612728  0.87645966 -0.52357672  1.10080195  0.20477053]
   [-1.09220754  1.89013039 -2.54671751 -0.64557611 -0.21614024]
   [ 0.19228126 -0.42253472  0.48539871  1.48719867  0.92300749]
   [-2.2124653  -0.33681882 -0.37620104  0.83220113 -0.72811256]]]


 [[[-1.04141408  1.39777605  0.85842558 -0.35631033  1.48191734]
   [ 0.1460079  -0.30437835 -0.00682851 -0.87972956 -1.11862279]
   [ 0.37481202  1.30371004 -1.10119055 -1.33913743  0.31165309]
   [-0.92682441 -

In [328]:
print(np.eye(3,4,1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [329]:
print(np.diag([4,3,2,5,1]))

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 5 0]
 [0 0 0 0 1]]


In [330]:
print(np.diag(d1))

[ 0  5 10]


In [334]:
s=np.random.randint(1,10,size=9).reshape(3,3)
print(s)
vals=np.linalg.eigvals(s)
print(vals)
print("coeff:  ",np.corrcoef(s))

[[9 4 2]
 [6 1 5]
 [1 8 2]]
[13.21954446  4.         -5.21954446]
coeff:   [[ 1.          0.41931393 -0.36628972]
 [ 0.41931393  1.         -0.99833749]
 [-0.36628972 -0.99833749  1.        ]]


In [341]:
a1=np.random.randint(0,10,size=15).reshape(3,5)
print(a1)
a2=np.array([[1,2,3,4],[1,2,3,4],[5,6,7,8]])
print(a2)
uniq=np.unique(a2,axis=0)
print(uniq)
uniq1=np.unique(a2)
print(uniq1)

[[9 8 2 1 0]
 [8 7 7 9 4]
 [1 3 6 5 7]]
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [343]:
coerr=np.corrcoef(a1,a1)
print(coerr)

[[ 1.          0.35138211 -0.94295417  1.          0.35138211 -0.94295417]
 [ 0.35138211  1.         -0.55487095  0.35138211  1.         -0.55487095]
 [-0.94295417 -0.55487095  1.         -0.94295417 -0.55487095  1.        ]
 [ 1.          0.35138211 -0.94295417  1.          0.35138211 -0.94295417]
 [ 0.35138211  1.         -0.55487095  0.35138211  1.         -0.55487095]
 [-0.94295417 -0.55487095  1.         -0.94295417 -0.55487095  1.        ]]


In [376]:
a3=np.random.randint(0,5,size=9).reshape(3,3)
val,_=np.linalg.eig(a3)
vla=np.linalg.eigvals(a3)
print(val)
print(vla)

[ 2.87512979+0.j       -0.9375649 +0.715691j -0.9375649 -0.715691j]
[ 2.87512979+0.j       -0.9375649 +0.715691j -0.9375649 -0.715691j]


In [352]:
a11=np.random.randint(2,8,size=(5,5))
print(a11)
normalized=((a11-a11.min())/(a11.max()-a11.min()))
print(normalized)

[[3 6 5 6 6]
 [3 6 6 4 3]
 [3 6 5 5 7]
 [7 4 4 7 3]
 [3 2 7 4 5]]
[[0.2 0.8 0.6 0.8 0.8]
 [0.2 0.8 0.8 0.4 0.2]
 [0.2 0.8 0.6 0.6 1. ]
 [1.  0.4 0.4 1.  0.2]
 [0.2 0.  1.  0.4 0.6]]


In [356]:
print("matrix multiplication: ",np.dot(a11,a11))
print("element wise multiplication: ",a11*a11)

matrix multiplication:  [[102 120 142 133 119]
 [ 82 112 118 112 105]
 [ 98 118 145 130 121]
 [103 124 128 139 118]
 [ 79  98 113 109 110]]
element wise multiplication:  [[ 9 36 25 36 36]
 [ 9 36 36 16  9]
 [ 9 36 25 25 49]
 [49 16 16 49  9]
 [ 9  4 49 16 25]]


In [357]:
print("determinant: ",np.linalg.det(a11))
print("inverse: ",np.linalg.inv(a11))

determinant:  885.9999999999993
inverse:  [[-0.6523702   0.0496614   0.4717833   0.21444695 -0.03611738]
 [-0.10158014  0.19977427  0.14785553 -0.02370203 -0.19074492]
 [-0.00451467  0.14221219 -0.1489842  -0.06772009  0.16930023]
 [ 0.79909707 -0.17155756 -0.62979684 -0.01354402  0.03386005]
 [-0.20090293 -0.17155756  0.37020316 -0.01354402  0.03386005]]


In [359]:
ar=np.random.randint(1,20,size=(4,4))
print(ar)
print("mean: ",np.mean(ar),"\nstandard deviation: ", np.std(ar),"\ncorrelation coefficient: ",np.corrcoef(ar))
reshaped=ar.reshape(2,8)
print(reshaped)
print("determinant: ",np.linalg.det(ar))
print("eigen values: ",np.linalg.eigvals(ar))
normalized=((ar-ar.min())/(ar.max()-ar.min()))
print(normalized)
trans=np.transpose(ar)
print(np.dot(normalized,trans))

[[16 14 16 14]
 [ 1  9 14  5]
 [ 6  1 12 10]
 [12  6  6  6]]
mean:  9.25 
standard deviation:  4.815340071064556 
correlation coefficient:  [[ 1.          0.05191741  0.41610681  0.57735027]
 [ 0.05191741  1.          0.28084146 -0.74936331]
 [ 0.41610681  0.28084146  1.         -0.17159956]
 [ 0.57735027 -0.74936331 -0.17159956  1.        ]]
[[16 14 16 14  1  9 14  5]
 [ 6  1 12 10 12  6  6  6]]
determinant:  -4764.0
eigen values:  [36.80720496+0.j         -1.82969454+0.j          4.01124479+7.39250595j
  4.01124479-7.39250595j]
[[1.         0.86666667 1.         0.86666667]
 [0.         0.53333333 0.86666667 0.26666667]
 [0.33333333 0.         0.73333333 0.6       ]
 [0.73333333 0.33333333 0.33333333 0.33333333]]
[[56.26666667 27.13333333 27.53333333 28.4       ]
 [25.06666667 18.26666667 13.6        10.        ]
 [25.46666667 13.6        16.8        12.        ]
 [26.4        10.06666667 12.06666667 14.8       ]]


In [360]:
arr = np.array([1, 2, np.nan, 4, 5])
print(arr)

[ 1.  2. nan  4.  5.]


In [365]:
ar12=np.random.seed(0)
print(ar12)

None


In [367]:
ar1=np.where(np.isnan(arr),0,arr)
print(ar1)

[1. 2. 0. 4. 5.]


In [370]:
a0=np.intersect1d(a11,a1)
print(a0)

[2 3 4 5 6 7]


In [374]:
a = np.array([("ksmjs",23),("sksks",66)],
             dtype=[("name","U10"),("age","i4")])
print(a)

[('ksmjs', 23) ('sksks', 66)]


In [383]:
print(ar)
print(np.sum(ar,axis=0))

[[16 14 16 14]
 [ 1  9 14  5]
 [ 6  1 12 10]
 [12  6  6  6]]
[35 30 48 35]


In [386]:
d=np.linspace(1,10,9).reshape(3,3)
d

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])